// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-leaderboard.ts
var get_leaderboard_default = defineTool({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the CPNS CAT exam leaderboard: participant names, TWK/TIU/TKP scores, total score and duration, ranked best-first.",
  inputSchema: {
    limit: z.number().int().describe("How many entries to return (1-100, default 20)").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const pageLimit = Math.min(Math.max(Math.trunc(limit ?? 20), 1), 100);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_leaderboard", {
      page_limit: pageLimit,
      page_offset: 0
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((row, index) => ({
      rank: index + 1,
      name: row.name,
      twk: row.twk_score,
      tiu: row.tiu_score,
      tkp: row.tkp_score,
      total: row.total_score,
      duration_minutes: row.duration_minutes,
      passed: row.twk_score >= 65 && row.tiu_score >= 80 && row.tkp_score >= 166,
      finished_at: row.finished_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { entries: rows }
    };
  }
});

// src/lib/mcp/tools/get-exam-statistics.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_exam_statistics_default = defineTool2({
  name: "get_exam_statistics",
  title: "Get exam statistics",
  description: "Get aggregate CPNS CAT statistics: number of sessions by status, pass rate against the TWK 65 / TIU 80 / TKP 166 thresholds, and average scores.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("exam_sessions").select("status, twk_score, tiu_score, tkp_score, total_score, duration_minutes").is("deleted_at", null);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const sessions = data ?? [];
    const finished = sessions.filter((s) => s.status === "finished");
    const avg = (values) => values.length ? Math.round(values.reduce((a, b) => a + b, 0) / values.length * 10) / 10 : 0;
    const passed = finished.filter(
      (s) => s.twk_score >= 65 && s.tiu_score >= 80 && s.tkp_score >= 166
    ).length;
    const stats = {
      total_sessions: sessions.length,
      by_status: sessions.reduce((acc, s) => {
        acc[s.status] = (acc[s.status] ?? 0) + 1;
        return acc;
      }, {}),
      finished_count: finished.length,
      passed_count: passed,
      pass_rate_percent: finished.length ? Math.round(passed / finished.length * 1e3) / 10 : 0,
      average_twk: avg(finished.map((s) => s.twk_score)),
      average_tiu: avg(finished.map((s) => s.tiu_score)),
      average_tkp: avg(finished.map((s) => s.tkp_score)),
      average_total: avg(finished.map((s) => s.total_score)),
      average_duration_minutes: avg(finished.map((s) => s.duration_minutes ?? 0))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-exam-sessions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_exam_sessions_default = defineTool3({
  name: "list_exam_sessions",
  title: "List exam sessions",
  description: "List CPNS CAT exam sessions with participant name, status, progress and scores. Optionally filter by status or search by participant name.",
  inputSchema: {
    status: z2.string().describe("Filter by session status, e.g. ongoing, finished, aborted.").optional(),
    search: z2.string().describe("Case-insensitive participant name search.").optional(),
    limit: z2.number().int().describe("How many sessions to return (1-100, default 25).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(Math.trunc(limit ?? 25), 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("exam_sessions").select(
      "id, name, status, answered_count, total_questions, twk_score, tiu_score, tkp_score, total_score, duration_minutes, disqualification_reason, started_at, finished_at"
    ).is("deleted_at", null).order("started_at", { ascending: false }).limit(take);
    if (status?.trim()) query = query.eq("status", status.trim());
    if (search?.trim()) query = query.ilike("name", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-exam-packages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_exam_packages_default = defineTool4({
  name: "list_exam_packages",
  title: "List question packages",
  description: "List the CPNS CAT question packages (paket soal) with their name, description, question count and whether the package is currently active.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("exam_packages").select("*").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { packages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wwbywxaferinpovrlpzq";
var mcp_default = defineMcp({
  name: "cpns-cat-simulator",
  title: "CPNS CAT Simulator",
  version: "0.1.0",
  instructions: "Read-only tools for the CPNS CAT Simulator. Use `get_leaderboard` for rankings, `get_exam_statistics` for aggregate pass rates and averages, `list_exam_sessions` to inspect individual participant sessions, and `list_exam_packages` to see available question packages. Passing thresholds are TWK >= 65, TIU >= 80, TKP >= 166.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_leaderboard_default,
    get_exam_statistics_default,
    list_exam_sessions_default,
    list_exam_packages_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
